import CryptoKit
import Darwin
import Foundation

/// A pinned, owner-only root for call evidence. Relative paths are generated by
/// Eye, but every component is still checked so relocation or a malicious
/// symlink cannot redirect writes outside the managed tree.
final class SecureCallSpoolRoot: @unchecked Sendable {
    let root: URL
    private let rootDescriptor: Int32

    init(root: URL) throws {
        let standardized = root.standardizedFileURL
        try FileManager.default.createDirectory(
            at: standardized,
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700]
        )
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o700],
            ofItemAtPath: standardized.path
        )
        let descriptor = open(standardized.path, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
        guard descriptor >= 0 else {
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }
        var info = stat()
        guard fstat(descriptor, &info) == 0, (info.st_mode & S_IFMT) == S_IFDIR else {
            _ = close(descriptor)
            throw CallSpoolError.unsafePath
        }
        self.root = standardized
        rootDescriptor = descriptor
    }

    deinit { _ = close(rootDescriptor) }

    func createFile(relativePath: String) throws -> URL {
        let (url, handle) = try createWritableFile(relativePath: relativePath)
        try handle.close()
        return url
    }

    func createWritableFile(relativePath: String) throws -> (URL, FileHandle) {
        let components = try safeComponents(relativePath)
        let parent = try openParent(components: Array(components.dropLast()), create: true)
        defer { _ = close(parent) }
        let leaf = components.last!
        let descriptor = leaf.withCString {
            openat(parent, $0, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW, mode_t(0o600))
        }
        guard descriptor >= 0 else {
            if errno == EEXIST { throw CallSpoolError.fileAlreadyExists }
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }
        _ = fchmod(descriptor, mode_t(0o600))
        return (
            root.appendingPathComponent(relativePath),
            FileHandle(fileDescriptor: descriptor, closeOnDealloc: true)
        )
    }

    func containedURL(relativePath: String) throws -> URL {
        _ = try safeComponents(relativePath)
        let candidate = root.appendingPathComponent(relativePath).standardizedFileURL
        let prefix = root.path.hasSuffix("/") ? root.path : root.path + "/"
        guard candidate.path.hasPrefix(prefix) else { throw CallSpoolError.unsafePath }
        return candidate
    }

    func readPrefix(relativePath: String, byteCount: Int) throws -> Data {
        let components = try safeComponents(relativePath)
        let parent = try openParent(components: Array(components.dropLast()), create: false)
        defer { _ = close(parent) }
        let descriptor = components.last!.withCString {
            openat(parent, $0, O_RDONLY | O_NOFOLLOW)
        }
        guard descriptor >= 0 else {
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }
        var info = stat()
        guard fstat(descriptor, &info) == 0, (info.st_mode & S_IFMT) == S_IFREG else {
            _ = close(descriptor)
            throw CallSpoolError.unsafePath
        }
        let handle = FileHandle(fileDescriptor: descriptor, closeOnDealloc: false)
        defer { try? handle.close() }
        return try handle.read(upToCount: byteCount) ?? Data()
    }

    private func safeComponents(_ relativePath: String) throws -> [String] {
        let parts = relativePath.split(separator: "/", omittingEmptySubsequences: false)
        guard !relativePath.hasPrefix("/"), !parts.isEmpty,
              parts.allSatisfy({ !$0.isEmpty && $0 != "." && $0 != ".." }) else {
            throw CallSpoolError.unsafePath
        }
        return parts.map(String.init)
    }

    private func openParent(components: [String], create: Bool) throws -> Int32 {
        var current = dup(rootDescriptor)
        guard current >= 0 else {
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }
        do {
            for component in components {
                var next = component.withCString {
                    openat(current, $0, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
                }
                if next < 0, create, errno == ENOENT {
                    let made = component.withCString { mkdirat(current, $0, mode_t(0o700)) }
                    guard made == 0 || errno == EEXIST else {
                        throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
                    }
                    next = component.withCString {
                        openat(current, $0, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
                    }
                }
                guard next >= 0 else { throw CallSpoolError.unsafePath }
                _ = fchmod(next, mode_t(0o700))
                _ = close(current)
                current = next
            }
            return current
        } catch {
            _ = close(current)
            throw error
        }
    }
}

actor CallSpool {
    private struct PendingFinalization: Sendable {
        let chunk: CallSpoolChunk
        let id: Int64?
        let sha256: String
    }

    private let secureRoot: SecureCallSpoolRoot
    private let callID: Int64
    private let source: CallAudioSource
    private let policy: CallSpoolPolicy
    private let repository: CallRepository?
    private let mediaGeneration: Int
    private var epochs: [CallSpoolEpochDescriptor] = []
    private var gaps: [AudioIngressGap] = []
    private var chunks: [CallSpoolChunk] = []
    private var activeHandle: FileHandle?
    private var activeChunkID: Int64?
    private var currentSpanID: Int64?
    private var pendingFinalizations: [PendingFinalization] = []
    private var currentSample: Int64 = 0
    private var nextChunkSequence = 0
    private var watermark: CallSpoolWatermark?

    init(
        root: URL,
        callID: Int64,
        source: CallAudioSource,
        policy: CallSpoolPolicy,
        repository: CallRepository? = nil,
        mediaGeneration: Int = 0
    ) throws {
        guard policy.sampleRate > 0, policy.maxSamplesPerChunk > 0 else {
            throw CallSpoolError.invalidPolicy
        }
        secureRoot = try SecureCallSpoolRoot(root: root)
        self.callID = callID
        self.source = source
        self.policy = policy
        self.repository = repository
        self.mediaGeneration = mediaGeneration
    }

    func beginEpoch(_ descriptor: CallSpoolEpochDescriptor) async throws {
        try await retryPendingFinalizations()
        if let previous = epochs.last {
            guard descriptor.epoch > previous.epoch,
                  descriptor.startSample >= currentSample else {
                throw CallSpoolError.invalidEpoch
            }
            try await finalizeActiveChunk()
            if let repository, let currentSpanID {
                try await repository.closeSourceSpan(
                    id: currentSpanID,
                    endedAtMs: descriptor.startedAtMs,
                    endSample: currentSample,
                    endHostTimeNs: descriptor.startHostTimeNs
                )
            }
        } else {
            currentSample = descriptor.startSample
        }
        epochs.append(descriptor)
        currentSample = descriptor.startSample
        nextChunkSequence = 0
        if let repository {
            let span = try await repository.recordSourceSpan(
                CallSourceSpanDraft(
                    callId: callID,
                    source: source,
                    epoch: descriptor.epoch,
                    sampleRate: policy.sampleRate,
                    startedAtMs: descriptor.startedAtMs,
                    startSample: descriptor.startSample,
                    startHostTimeNs: descriptor.startHostTimeNs,
                    availability: .available
                )
            )
            currentSpanID = span.id
        }
    }

    @discardableResult
    func appendPCM16(
        _ samples: [Int16],
        ingressSequence: Int64,
        normalizedHostTimeNs: Int64
    ) async throws -> CallSpoolWatermark {
        try await retryPendingFinalizations()
        guard let epoch = epochs.last else { throw CallSpoolError.noActiveEpoch }
        var cursor = 0
        while cursor < samples.count {
            try await ensureActiveChunk(epoch: epoch)
            guard let index = chunks.indices.last else { throw CallSpoolError.noActiveEpoch }
            let used = chunks[index].endSample - chunks[index].startSample
            let available = policy.maxSamplesPerChunk - used
            let count = min(Int(available), samples.count - cursor)
            let data = pcm16LE(Array(samples[cursor..<(cursor + count)]))
            guard let activeHandle else { throw CallSpoolError.noActiveEpoch }
            try activeHandle.seekToEnd()
            try activeHandle.write(contentsOf: data)
            chunks[index].endSample += Int64(count)
            chunks[index].committedBytes += Int64(data.count)
            currentSample += Int64(count)
            cursor += count
            if chunks[index].endSample - chunks[index].startSample >= policy.maxSamplesPerChunk {
                try await finalizeActiveChunk()
            }
        }
        let next = CallSpoolWatermark(
            ingressSequence: ingressSequence,
            endSample: currentSample,
            normalizedHostTimeNs: normalizedHostTimeNs,
            committedBytes: chunks.reduce(0) { $0 + $1.committedBytes }
        )
        watermark = next
        return next
    }

    func recordGap(_ gap: AudioIngressGap) throws {
        guard gap.source == source else { throw CallSpoolError.invalidEpoch }
        gaps.append(gap)
    }

    func snapshot() -> CallSpoolSnapshot {
        CallSpoolSnapshot(
            callID: callID,
            source: source,
            sampleRate: policy.sampleRate,
            epochs: epochs,
            gaps: gaps,
            chunks: chunks,
            watermark: watermark
        )
    }

    func flushDurableWatermark() async throws -> CallSpoolWatermark? {
        try await retryPendingFinalizations()
        guard let index = chunks.indices.last, !chunks[index].finalized else { return watermark }
        try activeHandle?.synchronize()
        let frozenChunk = chunks[index]
        let frozenChunkID = activeChunkID
        let frozenWatermark = watermark
        try await persistChunk(frozenChunk, id: frozenChunkID, finalized: false)
        return frozenWatermark
    }

    @discardableResult
    func finish() async throws -> CallSpoolSnapshot {
        try await retryPendingFinalizations()
        try await finalizeActiveChunk()
        if let repository, let currentSpanID, let epoch = epochs.last {
            try await repository.closeSourceSpan(
                id: currentSpanID,
                endedAtMs: milliseconds(for: currentSample, epoch: epoch),
                endSample: currentSample,
                endHostTimeNs: watermark?.normalizedHostTimeNs ?? epoch.startHostTimeNs
            )
        }
        return snapshot()
    }

    private func ensureActiveChunk(epoch: CallSpoolEpochDescriptor) async throws {
        guard activeHandle == nil else { return }
        let candidateSequence = nextChunkSequence
        let relativePath = String(
            format: "calls/%lld/%@/epoch-%04d/chunk-%06d.pcm",
            callID,
            source.rawValue,
            epoch.epoch,
            candidateSequence
        )
        let draft = CallSpoolChunk(
            epoch: epoch.epoch,
            sequence: candidateSequence,
            startSample: currentSample,
            endSample: currentSample,
            relativePath: relativePath,
            committedBytes: 0,
            finalized: false
        )
        let rowID: Int64?
        if let repository, let currentSpanID {
            let row = try await repository.recordAudioChunk(
                CallAudioChunkDraft(
                    callId: callID,
                    sourceSpanId: currentSpanID,
                    source: source,
                    epoch: epoch.epoch,
                    sequence: candidateSequence,
                    mediaGeneration: mediaGeneration,
                    startSample: currentSample,
                    endSample: currentSample,
                    startMs: milliseconds(for: currentSample, epoch: epoch),
                    endMs: milliseconds(for: currentSample, epoch: epoch),
                    relativePath: relativePath,
                    bytes: 0,
                    sha256: nil,
                    finalized: false
                )
            )
            rowID = row.id
        } else {
            rowID = nil
        }
        // An actor call may have filled the same deterministic slot while the
        // repository write was suspended. Reuse that published state instead
        // of opening a second file or detaching the row ID.
        guard activeHandle == nil, nextChunkSequence == candidateSequence else { return }
        let (_, handle) = try secureRoot.createWritableFile(relativePath: relativePath)
        activeHandle = handle
        chunks.append(draft)
        activeChunkID = rowID
        nextChunkSequence += 1
    }

    private func finalizeActiveChunk() async throws {
        guard let activeHandle, let index = chunks.indices.last, !chunks[index].finalized else { return }
        try activeHandle.synchronize()
        try activeHandle.close()
        self.activeHandle = nil
        chunks[index].finalized = true
        let finalizedChunk = chunks[index]
        let hash = SHA256.hash(
            data: try secureRoot.readPrefix(
                relativePath: finalizedChunk.relativePath,
                byteCount: Int(finalizedChunk.committedBytes)
            )
        )
            .map { String(format: "%02x", $0) }
            .joined()
        let pending = PendingFinalization(
            chunk: finalizedChunk,
            id: activeChunkID,
            sha256: hash
        )
        pendingFinalizations.append(pending)
        activeChunkID = nil
        try await persist(pending)
        pendingFinalizations.removeAll { $0.chunk.relativePath == pending.chunk.relativePath }
    }

    private func retryPendingFinalizations() async throws {
        while let pending = pendingFinalizations.first {
            try await persist(pending)
            pendingFinalizations.removeFirst()
        }
    }

    private func persist(_ pending: PendingFinalization) async throws {
        try await persistChunk(
            pending.chunk,
            id: pending.id,
            finalized: true,
            sha256: pending.sha256
        )
    }

    private func persistChunk(
        _ chunk: CallSpoolChunk,
        id: Int64?,
        finalized: Bool,
        sha256: String? = nil
    ) async throws {
        guard let repository, let id,
              let epoch = epochs.last(where: { $0.epoch == chunk.epoch }) else { return }
        try await repository.updateAudioChunkProgress(
            id: id,
            endSample: chunk.endSample,
            endMs: milliseconds(for: chunk.endSample, epoch: epoch),
            bytes: chunk.committedBytes,
            sha256: sha256,
            finalized: finalized
        )
    }

    private func milliseconds(for sample: Int64, epoch: CallSpoolEpochDescriptor) -> Int64 {
        epoch.startedAtMs + Int64(
            (Double(sample - epoch.startSample) / Double(policy.sampleRate) * 1_000).rounded()
        )
    }

    private func pcm16LE(_ samples: [Int16]) -> Data {
        samples.reduce(into: Data(capacity: samples.count * 2)) { data, sample in
            var value = sample.littleEndian
            withUnsafeBytes(of: &value) { data.append(contentsOf: $0) }
        }
    }
}
