import SwiftUI

/// "Ask your memory": a natural-language question → a local LLM answers from the retrieved fragments
/// of your screen and conversation history (RAG, cross-lingual). Fully on-device — like "Ask Rewind", without the cloud.
struct AskView: View {
    @Environment(AppEnvironment.self) private var env

    var body: some View {
        Group {
            if let store = env.ask {
                AskBody(store: store)
            } else {
                ContentUnavailableView("Initializing…", systemImage: "questionmark.bubble")
            }
        }
        .navigationTitle("Ask")
    }
}

private struct AskBody: View {
    @Bindable var store: AskStore
    @Environment(AppEnvironment.self) private var env

    var body: some View {
        VStack(spacing: 0) {
            if store.messages.isEmpty {
                emptyState
            } else {
                conversation
            }
            Divider()
            inputBar
        }
    }

    private var conversation: some View {
        ScrollViewReader { proxy in
            ScrollView {
                LazyVStack(alignment: .leading, spacing: 14) {
                    ForEach(store.messages) { m in
                        MessageRow(message: m).id(m.id)
                    }
                    if store.busy {
                        HStack(spacing: 8) {
                            ProgressView().controlSize(.small)
                            Text("Thinking about your history…").foregroundStyle(.secondary)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .id("busy")
                    }
                }
                .padding(16)
            }
            .onChange(of: store.messages.count) {
                if let last = store.messages.last {
                    withAnimation { proxy.scrollTo(last.id, anchor: .bottom) }
                }
            }
        }
    }

    private var emptyState: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                if !store.llmReady {
                    GlassCard {
                        VStack(alignment: .leading, spacing: 8) {
                            Label("A local LLM is required", systemImage: "exclamationmark.triangle")
                                .font(.headline)
                            Text("Answers are generated by a local model (Ollama / LM Studio / mlx_lm.server) — "
                                 + "no cloud. Set the endpoint and model in Connections.")
                                .font(.callout).foregroundStyle(.secondary)
                            Button("Open Connections") { env.selectedSection = .connections }
                        }
                    }
                }
                GlassCard {
                    VStack(alignment: .leading, spacing: 10) {
                        Label("Ask your memory", systemImage: "sparkles").font(.headline)
                        Text("Ask a question in plain language — ZBS Eye will find the relevant moments in your screen and "
                             + "conversation history and answer from them, with links to the sources. All on-device.")
                            .font(.callout).foregroundStyle(.secondary)
                        ForEach(Self.examples, id: \.self) { ex in
                            Button { store.input = ex; store.send() } label: {
                                Label(ex, systemImage: "text.magnifyingglass").font(.callout)
                            }
                            .buttonStyle(.plain)
                            .foregroundStyle(.tint)
                            .disabled(!store.llmReady)
                        }
                    }
                }
            }
            .padding(16)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private var inputBar: some View {
        HStack(spacing: 10) {
            TextField(store.llmReady ? "Ask about your history…" : "First set up a local LLM in Connections",
                      text: $store.input, axis: .vertical)
                .textFieldStyle(.plain)
                .lineLimit(1...4)
                .onSubmit { store.send() }
                .disabled(store.busy)   // input is available even without an LLM: a real question → a hint, while easter eggs always work 🥚
            if !store.messages.isEmpty {
                Button { store.clear() } label: { Image(systemName: "trash") }
                    .buttonStyle(.borderless).help("Clear conversation")
            }
            Button { store.send() } label: {
                Image(systemName: "arrow.up.circle.fill").font(.title2)
            }
            .buttonStyle(.borderless)
            .disabled(!store.canSend)
        }
        .padding(12)
    }

    static let examples = [
        "What did I read about Swift concurrency this week?",
        "What was the last call about?",
        "What address did someone send me yesterday?",
    ]
}

private struct MessageRow: View {
    let message: AskStore.Message

    var body: some View {
        switch message.role {
        case .user:
            HStack {
                Spacer(minLength: 40)
                Text(message.text)
                    .padding(.horizontal, 12).padding(.vertical, 8)
                    .background(Color.accentColor.opacity(0.18),
                                in: RoundedRectangle(cornerRadius: 12, style: .continuous))
            }
        case .assistant:
            VStack(alignment: .leading, spacing: 8) {
                Text(message.text).textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                if message.truncated {
                    Text("Answer cut off by the length limit — rephrase it shorter for the full one.")
                        .font(.caption).foregroundStyle(.secondary)
                }
                if !message.sources.isEmpty {
                    VStack(alignment: .leading, spacing: 6) {
                        Text("Sources").font(.caption).foregroundStyle(.secondary)
                        ForEach(Array(message.sources.enumerated()), id: \.element.uniqueKey) { i, s in
                            SourceChip(index: i + 1, result: s)
                        }
                    }
                }
            }
            .padding(.trailing, 40)
        }
    }
}

private struct SourceChip: View {
    @Environment(AppEnvironment.self) private var env
    let index: Int
    let result: SearchResult

    var body: some View {
        // Clicking a citation → the exact frame in the timeline ("don't take my word for it — here's the proof"). That's what sets
        // "memory you trust" apart from a RAG demo, and it hedges against a weak local LLM.
        Button {
            env.selectedSection = .timeline
            Task { await env.timelineStore?.select(result) }
        } label: {
            HStack(alignment: .top, spacing: 6) {
                Text("[\(index)]").font(.caption.monospacedDigit()).foregroundStyle(.secondary)
                VStack(alignment: .leading, spacing: 1) {
                    Text(label).font(.caption).foregroundStyle(.secondary)
                    Text(result.snippet).font(.caption2).foregroundStyle(.tertiary).lineLimit(2)
                }
                Spacer(minLength: 0)
                Image(systemName: "arrow.up.forward.square").font(.caption2).foregroundStyle(.tertiary)
            }
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .help("Open this moment in the timeline")
    }

    private var label: String {
        let when = result.ts.formatted(date: .abbreviated, time: .shortened)
        let who = result.appName ?? result.bundleId ?? (result.kind == .audio ? "Audio" : "Screen")
        return "\(when) · \(who)"
    }
}
